### ISSUE TITLE
能否为 app 增加打开文件菜单

### ISSUE THREAD

**Issue by jyz0501** [jch12138/ncmdump-mac-gui#2]
以实现在 finder 中右键 在 ncmdump 中打开的功能

**Comment by jyz0501** [comment]
比如 CFBundleDocumentTypes 键

**Comment by jch12138** [comment]
最近在忙毕业论文，可能没太多时间弄😢，等搞完我看看有没有空改一改

**Comment by jyz0501** [comment]
好的，因为我在做一个自动转换的快捷方式，不会写代码只好用笨方法来监听网易云目录更新，然后将更新的文件获取，然后通过你这个 App 打开，就可以自动转换了，还能同时删除 ncm 文件，用脚本做的，卡在了这一步

**Comment by jch12138** [comment]
您好，我尝试更新了一下功能，应该可以满足你的要求，然后当你通过右键打开进行转换时，程序会静默运行，不会弹出窗口，全部转换完成后自动退出

**Comment by jch12138** [comment]
> 好的，因为我在做一个自动转换的快捷方式，不会写代码只好用笨方法来监听网易云目录更新，然后将更新的文件获取，然后通过你这个 App 打开，就可以自动转换了，还能同时删除 ncm 文件，用脚本做的，卡在了这一步


您好，我尝试更新了一下功能，应该可以满足你的要求，然后当你通过右键打开进行转换时，程序会静默运行，不会弹出窗口，全部转换完成后自动退出

**Comment by jyz0501** [comment]
> > 好的，因为我在做一个自动转换的快捷方式，不会写代码只好用笨方法来监听网易云目录更新，然后将更新的文件获取，然后通过你这个 App 打开，就可以自动转换了，还能同时删除 ncm 文件，用脚本做的，卡在了这一步
> 
> 
> 
> 
> 
> 您好，我尝试更新了一下功能，应该可以满足你的要求，然后当你通过右键打开进行转换时，程序会静默运行，不会弹出窗口，全部转换完成后自动退出
> 
> 
> 
> 

是这个意思，右键已可以发现匹配，但是使用后发现静默了，没生成任何文件。

**Comment by jyz0501** [comment]
macOs 13.5.2 打开无反应，不转换

**Comment by jch12138** [comment]
https://github.com/jch12138/ncmdump-mac-gui/assets/30290347/ab7212b2-6f92-4dae-bae2-c73ee343dc3f

我本地测试没有问题诶，你能录个屏看一下吗 @jyz0501

**Comment by jyz0501** [comment]
MacBookpro 13.5.2 M1 芯片
不能用https://github.com/jch12138/ncmdump-mac-gui/assets/26475546/19da4f76-a120-44f7-ab69-f7c5c122716b

**Comment by jyz0501** [comment]
我发现我多选几个 ncm 文件时，会有一个被解析出来，但是单选的时候不行呢

**Comment by jch12138** [comment]
> 我发现我多选几个 ncm 文件时，会有一个被解析出来，但是单选的时候不行呢

我看看能不能复现

**Comment by jch12138** [comment]
确实有这个问题，右键打开不太稳定，在app内手动选择文件没有问题，我看一下怎么修复

**Comment by jch12138** [comment]
https://github.com/jch12138/ncmdump-mac-gui/assets/30290347/c3d6dea8-fc6b-4825-a076-0256c65d0a47

13系统中有这个现象，我刚升级到14后就没有了，不知道啥原因，要不你升级一下🥲

**Comment by jyz0501** [comment]
> 
> 
> https://github.com/jch12138/ncmdump-mac-gui/assets/30290347/c3d6dea8-fc6b-4825-a076-0256c65d0a47
> 
> 
> 
> 13系统中有这个现象，我刚升级到14后就没有了，不知道啥原因，要不你升级一下🥲

确实，现在我在用 14.5 单选和多选都可以实现了
